import { BookingWizard } from "@/components/booking/BookingWizard";

// Sample data — replace with real Zenoti API data
const CATEGORIES = [
  {
    id: "hair",
    name: "Hair",
    color: "#5ca0a6",
    services: [
      { id: "h1", name: "Haircut - Female", description: "Professional haircut with shampoo, conditioning, and blowout finish.", durationMinutes: 60, price: 40, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s2"], subcategory: "Haircuts" },
      { id: "h2", name: "Haircut - Male", description: "Classic men's haircut with hot towel finish.", durationMinutes: 45, price: 40, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s2"], subcategory: "Haircuts" },
      { id: "h3", name: "Haircut - Child Female", description: "Haircut for children under 12.", durationMinutes: 30, price: 25, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s2"], subcategory: "Haircuts" },
      { id: "h4", name: "Haircut - Child Male", description: "Haircut for children under 12.", durationMinutes: 30, price: 25, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s2"], subcategory: "Haircuts" },
      { id: "h5", name: "Haircut Blowout Finish", description: "Haircut with a professional blowout styling finish.", durationMinutes: 75, price: 48, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s2"], subcategory: "Haircuts" },
      { id: "h6", name: "Haircut Thermal Blowout", description: "Haircut with thermal tools blowout finish.", durationMinutes: 90, price: 58, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s2"], subcategory: "Haircuts" },
      { id: "h7", name: "Beard Trim", description: "Precision beard shaping and trimming.", durationMinutes: 15, price: 16, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s2"], subcategory: "Haircuts" },
      { id: "hc1", name: "Color Consultation", description: "Complimentary consultation to discuss your color goals.", durationMinutes: 15, price: 0, depositRequired: null, requiresConsult: true, providerIds: ["s1", "s2"], subcategory: "Hair Color" },
      { id: "hc2", name: "Color Retouch", description: "Root touch-up color application.", durationMinutes: 60, price: 69, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s2"], subcategory: "Hair Color" },
      { id: "hc3", name: "All-Over Color or A Few Highlights", description: "Full single-process color or partial highlights.", durationMinutes: 90, price: 100, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s2"], subcategory: "Hair Color" },
      { id: "hc4", name: "Color + Partial Highlight", description: "Color retouch combined with partial highlights.", durationMinutes: 120, price: 131, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s2"], subcategory: "Hair Color" },
      { id: "hc5", name: "Full Highlight", description: "Full head highlight service.", durationMinutes: 120, price: 163, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s2"], subcategory: "Hair Color" },
      { id: "hc6", name: "Custom Color", description: "Multi-technique custom color service.", durationMinutes: 150, price: 194, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s2"], subcategory: "Hair Color" },
      { id: "hc7", name: "Color Transformation", description: "Major color change requiring multiple techniques.", durationMinutes: 240, price: 262, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s2"], subcategory: "Hair Color" },
      { id: "hs1", name: "Blowout Finish - Female", description: "Professional blowout styling.", durationMinutes: 30, price: 25, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s2"], subcategory: "Styling" },
      { id: "hs2", name: "Blowout Thermal Style", description: "Blowout with thermal styling tools.", durationMinutes: 45, price: 45, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s2"], subcategory: "Styling" },
      { id: "hs3", name: "Special Occasion Style - Junior Level", description: "Updo or special event styling by a junior stylist.", durationMinutes: 60, price: 81, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s2"], subcategory: "Styling" },
      { id: "hs4", name: "Special Occasion Style - Senior Level", description: "Updo or special event styling by a senior stylist.", durationMinutes: 60, price: 93, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s2"], subcategory: "Styling" },
      { id: "hco1", name: "Haircut Consultation", description: "Complimentary consultation for haircut services.", durationMinutes: 15, price: 0, depositRequired: null, requiresConsult: true, providerIds: ["s1", "s2"], subcategory: "Consultation" },
      { id: "hco2", name: "Keratin Consultation", description: "Complimentary consultation for keratin treatments.", durationMinutes: 15, price: 0, depositRequired: null, requiresConsult: true, providerIds: ["s1", "s2"], subcategory: "Consultation" },
      { id: "hco3", name: "Hair Extension Consultation", description: "Complimentary consultation for hair extensions.", durationMinutes: 15, price: 0, depositRequired: null, requiresConsult: true, providerIds: ["s1", "s2"], subcategory: "Consultation" },
      { id: "hco4", name: "Bridal Style Consultation", description: "Complimentary consultation for bridal styling.", durationMinutes: 15, price: 0, depositRequired: null, requiresConsult: true, providerIds: ["s1", "s2"], subcategory: "Consultation" },
    ],
  },
  {
    id: "barber",
    name: "Barber",
    color: "#5ca0a6",
    services: [
      { id: "b1", name: "Barber Haircut", description: "Includes a stress-relieving scalp and shoulder massage, hot towel ritual, shampoo, precision cut and style.", durationMinutes: 45, price: 32, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s3"], subcategory: "Barber Services" },
      { id: "b2", name: "Barber Fade", description: "Precision fade haircut with detailed blending.", durationMinutes: 45, price: 38, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s3"], subcategory: "Barber Services" },
      { id: "b3", name: "Beard Trim", description: "Professional beard shaping and trimming.", durationMinutes: 15, price: 15, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s3"], subcategory: "Barber Services" },
      { id: "b4", name: "Hot Towel Shave", description: "Classic straight-razor hot towel shave experience.", durationMinutes: 30, price: 28, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s3"], subcategory: "Barber Services" },
      { id: "b5", name: "Express Hot Towel Facial", description: "Quick rejuvenating facial with hot towel treatment.", durationMinutes: 30, price: 28, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s3"], subcategory: "Barber Services" },
      { id: "b6", name: "Hot Towel Shave + Facial", description: "Complete shave and facial experience.", durationMinutes: 60, price: 46, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s3"], subcategory: "Barber Services" },
      { id: "b7", name: "Edge Up or Line Up", description: "Clean up hairline and edges.", durationMinutes: 15, price: 12, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s3"], subcategory: "Barber Services" },
      { id: "b8", name: "Neck Shave", description: "Neckline cleanup with hot towel.", durationMinutes: 15, price: 12, depositRequired: null, requiresConsult: false, providerIds: ["s1", "s3"], subcategory: "Barber Services" },
    ],
  },
  {
    id: "nails",
    name: "Nails",
    color: "#5ca0a6",
    services: [
      { id: "n1", name: "Aveda Manicure", description: "Classic Aveda manicure with hand massage.", durationMinutes: 30, price: 40, depositRequired: null, requiresConsult: false, providerIds: ["s4"], subcategory: "Natural Nails" },
      { id: "n2", name: "Aveda Pedicure", description: "Relaxing Aveda pedicure with foot massage.", durationMinutes: 60, price: 65, depositRequired: null, requiresConsult: false, providerIds: ["s4"], subcategory: "Natural Nails" },
      { id: "n3", name: "Hot Stone Pedicure", description: "Luxurious pedicure with hot stone massage.", durationMinutes: 75, price: 101, depositRequired: null, requiresConsult: false, providerIds: ["s4"], subcategory: "Natural Nails" },
      { id: "n4", name: "Express Pedicure", description: "Quick pedicure service.", durationMinutes: 30, price: 54, depositRequired: null, requiresConsult: false, providerIds: ["s4"], subcategory: "Natural Nails" },
      { id: "n5", name: "Aveda Manicure + Gel Polish", description: "Aveda manicure with gel polish finish.", durationMinutes: 45, price: 63, depositRequired: null, requiresConsult: false, providerIds: ["s4"], subcategory: "Gel Nails" },
      { id: "n6", name: "Aveda Pedicure + Gel Polish", description: "Aveda pedicure with gel polish finish.", durationMinutes: 75, price: 85, depositRequired: null, requiresConsult: false, providerIds: ["s4"], subcategory: "Gel Nails" },
      { id: "n7", name: "Gel Polish Change for Hands", description: "Gel polish removal and reapplication.", durationMinutes: 30, price: 48, depositRequired: null, requiresConsult: false, providerIds: ["s4"], subcategory: "Gel Nails" },
      { id: "n8", name: "Hard Gel Nails with Tips", description: "Full set of hard gel nails with tips.", durationMinutes: 90, price: 105, depositRequired: null, requiresConsult: false, providerIds: ["s4"], subcategory: "Hard Gel" },
      { id: "n9", name: "Hard Gel Fill", description: "Hard gel fill maintenance.", durationMinutes: 60, price: 75, depositRequired: null, requiresConsult: false, providerIds: ["s4"], subcategory: "Hard Gel" },
    ],
  },
  {
    id: "skin",
    name: "Skin",
    color: "#5ca0a6",
    services: [
      { id: "sk1", name: "Standard Facial - 60 min", description: "Customized 60-minute facial treatment.", durationMinutes: 60, price: 88, depositRequired: null, requiresConsult: false, providerIds: ["s5"], subcategory: "Standard Facials" },
      { id: "sk2", name: "Standard Facial - 90 min", description: "Extended 90-minute facial experience.", durationMinutes: 90, price: 105, depositRequired: null, requiresConsult: false, providerIds: ["s5"], subcategory: "Standard Facials" },
      { id: "sk3", name: "Dermaplane", description: "Exfoliating dermaplaning treatment.", durationMinutes: 60, price: 88, depositRequired: null, requiresConsult: false, providerIds: ["s5"], subcategory: "Standard Facials" },
      { id: "sk4", name: "Perfecting Plant Peel", description: "Natural plant-based peel for skin rejuvenation.", durationMinutes: 45, price: 83, depositRequired: null, requiresConsult: false, providerIds: ["s5"], subcategory: "Standard Facials" },
      { id: "sk5", name: "Signature HydraFacial", description: "Signature HydraFacial treatment for deep cleansing and hydration.", durationMinutes: 60, price: 199, depositRequired: null, requiresConsult: false, providerIds: ["s5"], subcategory: "HydraFacials" },
      { id: "sk6", name: "Deluxe HydraFacial", description: "Enhanced HydraFacial with boosters.", durationMinutes: 75, price: 250, depositRequired: null, requiresConsult: false, providerIds: ["s5"], subcategory: "HydraFacials" },
      { id: "sk7", name: "Platinum HydraFacial", description: "Premium HydraFacial with LED light therapy.", durationMinutes: 90, price: 325, depositRequired: null, requiresConsult: false, providerIds: ["s5"], subcategory: "HydraFacials" },
      { id: "sk8", name: "Chemical Peel with Homecare Kit", description: "Professional chemical peel with take-home aftercare.", durationMinutes: 45, price: 150, depositRequired: null, requiresConsult: false, providerIds: ["s5"], subcategory: "Chemical Peels" },
      { id: "sk9", name: "Skin Care Consultation", description: "Complimentary skin analysis and treatment consultation.", durationMinutes: 15, price: 0, depositRequired: null, requiresConsult: true, providerIds: ["s5"], subcategory: "Consultation" },
    ],
  },
  {
    id: "body-wellness",
    name: "Body + Wellness",
    color: "#5ca0a6",
    services: [
      { id: "bw1", name: "Aroma Massage - 60 min", description: "Full body Aveda aroma massage.", durationMinutes: 60, price: 98, depositRequired: null, requiresConsult: false, providerIds: ["s6"], subcategory: "Massage Therapy" },
      { id: "bw2", name: "Aroma Massage - 90 min", description: "Extended Aveda aroma massage.", durationMinutes: 90, price: 130, depositRequired: null, requiresConsult: false, providerIds: ["s6"], subcategory: "Massage Therapy" },
      { id: "bw3", name: "Hot Stone Massage", description: "Therapeutic massage with heated stones.", durationMinutes: 90, price: 186, depositRequired: null, requiresConsult: false, providerIds: ["s6"], subcategory: "Massage Therapy" },
      { id: "bw4", name: "CBD Body Glow", description: "CBD-infused body treatment for deep relaxation.", durationMinutes: 60, price: 115, depositRequired: null, requiresConsult: false, providerIds: ["s6"], subcategory: "Massage Therapy" },
      { id: "bw5", name: "Reboot IV", description: "Recover fast — alleviates nausea, headaches and dehydration. Vitamins and minerals to help you bounce back.", durationMinutes: 45, price: 200, depositRequired: null, requiresConsult: false, providerIds: ["s6"], subcategory: "IV Nutrition Therapy" },
      { id: "bw6", name: "Myer's Cocktail IV", description: "Classic IV vitamin infusion for wellness.", durationMinutes: 45, price: 100, depositRequired: null, requiresConsult: false, providerIds: ["s6"], subcategory: "IV Nutrition Therapy" },
      { id: "bw7", name: "Immunity IV", description: "Immune-boosting IV vitamin therapy.", durationMinutes: 45, price: 150, depositRequired: null, requiresConsult: false, providerIds: ["s6"], subcategory: "IV Nutrition Therapy" },
      { id: "bw8", name: "Inner Beauty IV", description: "IV therapy for radiant skin, hair, and nails.", durationMinutes: 45, price: 200, depositRequired: null, requiresConsult: false, providerIds: ["s6"], subcategory: "IV Nutrition Therapy" },
    ],
  },
  {
    id: "injectables",
    name: "Injectables",
    color: "#5ca0a6",
    services: [
      { id: "i1", name: "Neurotoxin Consultation with Service", description: "Botox/neurotoxin consultation with same-day treatment.", durationMinutes: 30, price: 0, depositRequired: null, requiresConsult: true, providerIds: ["s5"], subcategory: "Injectables" },
      { id: "i2", name: "Filler Consultation with Service", description: "Dermal filler consultation with same-day treatment.", durationMinutes: 30, price: 0, depositRequired: null, requiresConsult: true, providerIds: ["s5"], subcategory: "Injectables" },
      { id: "i3", name: "Filler Dissolver", description: "Hyaluronidase treatment to dissolve filler.", durationMinutes: 30, price: 175, depositRequired: null, requiresConsult: false, providerIds: ["s5"], subcategory: "Injectables" },
    ],
  },
  {
    id: "makeup-brows-lashes",
    name: "Makeup Brows + Lashes",
    color: "#5ca0a6",
    services: [
      { id: "m1", name: "Makeup Application - Advanced Artist", description: "Full face makeup by an advanced artist.", durationMinutes: 45, price: 80, depositRequired: null, requiresConsult: false, providerIds: ["s7"], subcategory: "Makeup" },
      { id: "m2", name: "Makeup Application - Senior Artist", description: "Full face makeup by a senior artist.", durationMinutes: 45, price: 100, depositRequired: null, requiresConsult: false, providerIds: ["s7"], subcategory: "Makeup" },
      { id: "m3", name: "Lash Lift", description: "Semi-permanent lash lift.", durationMinutes: 60, price: 80, depositRequired: null, requiresConsult: false, providerIds: ["s7"], subcategory: "Lash Specialties" },
      { id: "m4", name: "Lash Tinting", description: "Lash tinting for darker, more defined lashes.", durationMinutes: 15, price: 23, depositRequired: null, requiresConsult: false, providerIds: ["s7"], subcategory: "Lash Specialties" },
      { id: "m5", name: "Lash Lift + Tint", description: "Combined lash lift and tint.", durationMinutes: 60, price: 100, depositRequired: null, requiresConsult: false, providerIds: ["s7"], subcategory: "Lash Specialties" },
      { id: "m6", name: "Brow Lamination", description: "Brow lamination for fuller, styled brows.", durationMinutes: 45, price: 60, depositRequired: null, requiresConsult: false, providerIds: ["s7"], subcategory: "Brow Lamination Services" },
      { id: "m7", name: "Brow Lamination + Tint", description: "Brow lamination with tint.", durationMinutes: 60, price: 80, depositRequired: null, requiresConsult: false, providerIds: ["s7"], subcategory: "Brow Lamination Services" },
      { id: "m8", name: "Microblading", description: "Semi-permanent brow microblading.", durationMinutes: 120, price: 375, depositRequired: 100, requiresConsult: false, providerIds: ["s7"], subcategory: "Microblading Services" },
    ],
  },
  {
    id: "waxing",
    name: "Waxing",
    color: "#5ca0a6",
    services: [
      { id: "w1", name: "Brow Wax", description: "Precision brow shaping wax.", durationMinutes: 15, price: 20, depositRequired: null, requiresConsult: false, providerIds: ["s7", "s4"], subcategory: "Waxing Services" },
      { id: "w2", name: "Lip Wax", description: "Upper lip waxing.", durationMinutes: 10, price: 20, depositRequired: null, requiresConsult: false, providerIds: ["s7", "s4"], subcategory: "Waxing Services" },
      { id: "w3", name: "Chin Wax", description: "Chin area waxing.", durationMinutes: 10, price: 20, depositRequired: null, requiresConsult: false, providerIds: ["s7", "s4"], subcategory: "Waxing Services" },
      { id: "w4", name: "Full Face Wax", description: "Complete face waxing service.", durationMinutes: 30, price: 50, depositRequired: null, requiresConsult: false, providerIds: ["s7", "s4"], subcategory: "Waxing Services" },
      { id: "w5", name: "Under Arm Wax", description: "Underarm waxing.", durationMinutes: 15, price: 40, depositRequired: null, requiresConsult: false, providerIds: ["s7", "s4"], subcategory: "Waxing Services" },
      { id: "w6", name: "Bikini Wax", description: "Standard bikini line wax.", durationMinutes: 15, price: 40, depositRequired: null, requiresConsult: false, providerIds: ["s7", "s4"], subcategory: "Waxing Services" },
      { id: "w7", name: "Brazilian Wax", description: "Full Brazilian waxing service.", durationMinutes: 30, price: 82, depositRequired: null, requiresConsult: false, providerIds: ["s7", "s4"], subcategory: "Waxing Services" },
      { id: "w8", name: "Full Leg Wax", description: "Complete leg waxing.", durationMinutes: 45, price: 74, depositRequired: null, requiresConsult: false, providerIds: ["s7", "s4"], subcategory: "Waxing Services" },
    ],
  },
  {
    id: "laser-hair-removal",
    name: "Laser Hair Removal",
    color: "#5ca0a6",
    services: [
      { id: "l1", name: "Upper Lip", description: "Laser hair removal for upper lip area.", durationMinutes: 15, price: 90, depositRequired: null, requiresConsult: false, providerIds: ["s5"], subcategory: "Laser Hair Removal" },
      { id: "l2", name: "Chin", description: "Laser hair removal for chin area.", durationMinutes: 15, price: 100, depositRequired: null, requiresConsult: false, providerIds: ["s5"], subcategory: "Laser Hair Removal" },
      { id: "l3", name: "Under Arm", description: "Laser hair removal for underarm area.", durationMinutes: 15, price: 130, depositRequired: null, requiresConsult: false, providerIds: ["s5"], subcategory: "Laser Hair Removal" },
      { id: "l4", name: "Bikini Line", description: "Laser hair removal for bikini line.", durationMinutes: 15, price: 150, depositRequired: null, requiresConsult: false, providerIds: ["s5"], subcategory: "Laser Hair Removal" },
      { id: "l5", name: "Brazilian", description: "Laser hair removal for full Brazilian area.", durationMinutes: 30, price: 225, depositRequired: null, requiresConsult: false, providerIds: ["s5"], subcategory: "Laser Hair Removal" },
      { id: "l6", name: "Full Face", description: "Laser hair removal for full face.", durationMinutes: 30, price: 200, depositRequired: null, requiresConsult: false, providerIds: ["s5"], subcategory: "Laser Hair Removal" },
      { id: "l7", name: "Full Leg", description: "Laser hair removal for full legs.", durationMinutes: 60, price: 450, depositRequired: null, requiresConsult: false, providerIds: ["s5"], subcategory: "Laser Hair Removal" },
    ],
  },
];

const STAFF = [
  { id: "s1", firstName: "Sarah", lastName: "Mitchell", color: "#5ca0a6" },
  { id: "s2", firstName: "Jessica", lastName: "Taylor", color: "#b560f2" },
  { id: "s3", firstName: "Marcus", lastName: "Johnson", color: "#4a8d93" },
  { id: "s4", firstName: "Emily", lastName: "Chen", color: "#c580f5" },
  { id: "s5", firstName: "Dr. Lauren", lastName: "Davis", color: "#5ca0a6" },
  { id: "s6", firstName: "Amanda", lastName: "Rivera", color: "#b560f2" },
  { id: "s7", firstName: "Nicole", lastName: "Park", color: "#4a8d93" },
];

export default function BookPage() {
  return <BookingWizard categories={CATEGORIES} staff={STAFF} />;
}
